### ISSUE TITLE
Update pip version

### ISSUE THREAD

**Issue by mogenson** [t184256/xontrib-prompt-vi-mode#2]
The 'xpip' alias seems to be fetching an out of date version of this xontrib from [pypi.org](https://pypi.org/project/xontrib-prompt-vi-mode/). That version doesn't have the fix detailed in issue #1.

Could you update the version hosted on pip?

**Comment by t184256** [comment]
Done, 0.1.3: https://pypi.org/project/xontrib-prompt-vi-mode/#history
